### ISSUE TITLE
Don't add pre-releases and retired versions to docs_config.js

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexdocs#10]
We'd still include a pre-release if it's the latest version though.

cc @josevalim @ericmj

**Comment by ericmj** [comment]
I am not sure about this. It could still be useful to list those. We could add `(retired)` for retired versions though.

**Comment by josevalim** [comment]
@ericmj I think nobody should be navigating to a pre-release API unless they are trying out something new. It also hurts the UI a bit because the dropdown looks really disorganized.

**Comment by ericmj** [comment]
When they are trying something new they will probably need the docs :). Users might think the docs do not exist if they do not appear in the dropdown, so they wont realize they can go through hex.pm or modify the URL. I agree that it makes the dropdown a bit more disorganized though.

**Comment by josevalim** [comment]
To clarify, we will include the latest pre-release, as long as there is
nothing released after it.

I am not sure about retired versions though. I would keep them there for
now with no note or distinction. That’s the simplest approach and we can
collect feedback.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
Makes sense. Let's do that 👍
