### ISSUE TITLE
Possibility of adding opensearch.xml

### ISSUE THREAD

**Issue by ffimnsr** [hexpm/hexdocs#14]
Hi guys, just like `hex.pm` is it also possible to add `opensearch.xml` to `hexdocs.pm`?

https://github.com/hexpm/hexpm/blob/master/lib/hexpm_web/templates/open_search/opensearch.xml.eex

**Comment by wojtekmach** [comment]
Unfortunately that's a bit tricky given hexdocs.pm doesn't currently have a search page that opensearch.xml would land on. We only have client-side search on the static index.html page, so the first step would be to adding a search endpoint served by a Phoenix controller.

We don't plan to work on this but if someone would like to explore this, please let us know! Sorry for radio silence :)
