### ISSUE TITLE
When copy/pasting function names, exclude metadata

### ISSUE THREAD

**Issue by Doerge** [hexpm/hexdocs#15]
Thanks for a great project! 🎉 

I'm not 100% sure this is the correct repo to post in, so pardon me, if it belongs somewhere else.

I often find myself using hexdocs and then copy/pasting function or attribute names to my editor. When I do that I get a bit of extra meta data, other than the name:
<img width="925" alt="Screenshot 2020-03-13 at 11 31 24" src="https://user-images.githubusercontent.com/3216279/76613593-bba81300-651e-11ea-9f52-8e94f009e384.png">
becomes
<img width="419" alt="Screenshot 2020-03-13 at 11 35 39" src="https://user-images.githubusercontent.com/3216279/76613622-c8c50200-651e-11ea-9ba6-30b59711e7dc.png">
in my editor.

It would be nice if I would only get `add_error` instead of `functionadd_error` in this example.

**Comment by wojtekmach** [comment]
HexDocs.pm is only concerned with docs hosting, not the docs itself. The bug is in https://github.com/elixir-lang/ex_doc; a PR would be appreciated!

**Comment by wojtekmach** [comment]
fwiw copy-pasting the name from the _spec_ doesn't have this issue :) but yeah, we should definitely fix this.

**Comment by wojtekmach** [comment]
I saw that removing "display: inline-block" from the element fixes this but no idea what's going on.

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/76071/76614846-1fcbd680-6521-11ea-9cc7-9ace018736b0.png">
