### ISSUE TITLE
Per-package sitemaps

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/hexdocs#18]
1. [x] On docs upload, automatically create a `/<package>/sitemap.xml` file. This is a sitemap of all `*.html` files for that package. We'll only have top-level sitemap so no `/<package>/<version>/sitemap.xml`. This is only for public packages.

2. [x] Run a script that retroactively creates package sitemap for all packages.

3. [x] Change the global sitemap to become sitemap index (https://www.sitemaps.org/protocol.html#index) that link to each package's sitemap.

**Comment by wojtekmach** [comment]
Done! 🎉

**Comment by wojtekmach** [comment]
We couldn't create sitemaps for these 6 packages:

```elixir
["docs/bbmustache-1.0.0.tar.gz", "docs/rebar3_eqc-0.0.5.tar.gz",
 "docs/providers-1.4.1.tar.gz", "docs/neotoma-1.7.3.tar.gz",
 "docs/erlsh-0.1.0.tar.gz", "docs/enotify-0.1.0.tar.gz"]
```

and that's because we were getting the following error:

```
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Interactive Elixir (1.10.4) - press Ctrl+C to exit (type h() ENTER for help)
```

```elixir
iex> :inets.start(); :ssl.start(); {:ok, {_, _, body}} = :httpc.request("https://repo.hex.pm/docs/enotify-0.1.0.tar.gz"); :zlib.gunzip(body)
** (ErlangError) Erlang error: :data_error
    :zlib.inflate_nif(#Reference<0.1437844419.344850435.45344>, 8192, 16384, 0)
    :zlib.dequeue_all_chunks_1/3
    :zlib.inflate/3
    :zlib.gunzip/1
```

I could unpack from macOS Finder as well as using `tar`:

```
$ tar xzf enotify-0.1.0.tar.gz
```

but not with gunzip (but I could gunzip other downloaded docs tarballs)

```
$ gunzip enotify-0.1.0.tar.gz
gunzip: enotify-0.1.0.tar.gz: not in gzip format
```

so not sure what's going on.

**Comment by wojtekmach** [comment]
it's unclear how these tars were generated in the first place, we can't extract them even on older OTP releases. Here's on 17.3.3:

```
$ ID=17.3.3-ubuntu-xenial-20200212; docker run --rm hexpm/erlang:$ID erl -noshell -eval 'inets:start(), ssl:start(), {ok, {_, _, Body}} = httpc:request("https://repo.hex.pm/docs/enotify-0.1.0.tar.gz"), zlib:gunzip(Body).'
{"init terminating in do_boot",{data_error,[{zlib,call,3,[]},{zlib,inflate,2,[]},{zlib,gunzip,1,[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,657}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
```

Closing this then.

**Comment by wojtekmach** [comment]
We're going to do the following:

1.  remove these docs tarballs
2. mark appropriate entries in the hexpm db as `has_docs = false`.

**Comment by ericmj** [comment]
@wojtekmach Have you delete the bad tarballs? If not, I can do it.

**Comment by wojtekmach** [comment]
@ericmj No, I still haven't. Thanks! You can leave it to me too, will eventually get to it.

**Comment by wojtekmach** [comment]
I executed the following script on prod:

```
files = [
  "docs/bbmustache-1.0.0.tar.gz",
  "docs/rebar3_eqc-0.0.5.tar.gz",
  "docs/providers-1.4.1.tar.gz",
  "docs/neotoma-1.7.3.tar.gz",
  "docs/erlsh-0.1.0.tar.gz",
  "docs/enotify-0.1.0.tar.gz"
]

IO.inspect(files)

for file <- files do
  [package, version] = file |> Path.basename(".tar.gz") |> String.split("-")
  release = Hexpm.Repository.Releases.get("hexpm", package, version)
  release |> Ecto.Changeset.change(has_docs: false) |> Hexpm.Repo.update!()
end

IO.inspect(Hexpm.Store.delete_many(:repo_bucket, files))
```
