### ISSUE TITLE
Search can't find anything in code blocks or back-ticks?

### ISSUE THREAD

**Issue by garthk** [hexpm/hexdocs#21]
I'd expect a search for ["handle_errors"](https://hexdocs.pm/plug/search.html?q=handle_errors) in the Plug documentation to bring up [Plug.ErrorHandler](https://hexdocs.pm/plug/Plug.ErrorHandler.html), but it doesn't?

**Comment by ericmj** [comment]
Please report this issue to https://github.com/elixir-lang/ex_doc which generates the docs.
