### ISSUE TITLE
Sitemap files for Elixir core apps are missing

### ISSUE THREAD

**Issue by eksperimental** [hexpm/hexdocs#23]
I just noticed in the main sitemap.xml the links to the sitemaps for `elixir`, `mix` _et al._
The  sitemap.xml files for such apps are also missing.

Related issue: https://github.com/hexpm/hexdocs/issues/18

**Comment by ericmj** [comment]
The elixir docs are built and uploaded in https://github.com/hexpm/bob and the sitemaps are built in this project https://github.com/hexpm/hexdocs which makes this a bit tricky. I think we can reuse the temporary queue event @wojtekmach created https://github.com/hexpm/hexdocs/blob/master/lib/hexdocs/queue.ex#L51 by using [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/sqs/send-message.html) in bob to send this event.

@wojtekmach It's a bit hacky, do you have a better idea?

**Comment by wojtekmach** [comment]
We've moved Elixir docs uploads from bob to GHA and this is now done.
