### ISSUE TITLE
Per-version sitemaps

### ISSUE THREAD

**Issue by eksperimental** [hexpm/hexdocs#24]
As of now I see it is only the stable version that gets a sitemap.
I am wondering if this is correct, as new major versions come up, the documentation may be totally different

**Comment by ericmj** [comment]
Since we try to get search engines to only link to the latest version of the documentation I think sitemaps for other versions are not necessary.

**Comment by eksperimental** [comment]
Ideally I would prefer to have a sitemap per major version

**Comment by ericmj** [comment]
What purpose would it serve since we point the canonical url to the latest version only?

**Comment by eksperimental** [comment]
> What purpose would it serve since we point the canonical url to the latest version only?

I see.
So older documentation may link to URL that may no longer exist due to the API changing in new major versions?

**Comment by ericmj** [comment]
No, the links stay the same. Canonical url is only for search engine results.

**Comment by ericmj** [comment]
Closing this, but let me know if you still have concerns and we can reopen.
