### ISSUE TITLE
Add checks for common errors on hexdocs 404 page

### ISSUE THREAD

**Issue by joshdcuneo** [hexpm/hexdocs#25]
It looks like hexpm/hexpm#618 belongs on this repo.

If that is correct I'd be happy to work on it.

**Original issue**
Comment from @josevalim in [#617 (comment)](https://github.com/hexpm/hexpm/issues/617#issuecomment-357417808):

> I am thinking we should include a javascript in the 404 page. The javascript would parse the path and send it to Hex API asking: is this a valid package path? If so, does the package exist? If so, does this version have docs? The Hex API would return important information like the package name, version and docs availability so we can build a reasonable error message to users, possibly linking to the package+version or the package page, so they can report the bug in the proper place.

**Comment by ericmj** [comment]
The issue is on hexpm for visibility. The actual repository is on https://github.com/hexpm/hexdocs-static.

The issue is up for grabs so if you want to work on then go ahead! 💜
