### ISSUE TITLE
Next, previous page buttons

### ISSUE THREAD

**Issue by sabit990928** [hexpm/hexdocs#26]
Hey all! 
I'm not sure where should I put this issue, but this place seems relative a bit.
I ran through bunch of elixir/phoenix/liveView guides, docs and love reading it when have time. 
There's addition which I recommend you guys to add. Usually when people read through the guide, they go from top to bottom. So I think it'll be better if they can move to next article by clicking `Next Article` button in the bottom of each page. Especially for me it's not comfortable, UX friendly behavior to move between articles through the sidebar. 

What's your thoughts about that one?

**Comment by wojtekmach** [comment]
We already have that!

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/76071/127626074-737cb4b9-2266-41cc-94fc-7b9dfa4b7663.png">

(https://hexdocs.pm/elixir/compatibility-and-deprecations.html)

Library authors need to use a recent enough version of ExDoc.

**Comment by sabit990928** [comment]
Sorry, somehow missed that. Thanks anyway @wojtekmach!
