### ISSUE TITLE
URLs with % in query string fail

### ISSUE THREAD

**Issue by josevalim** [hexpm/hexdocs#38]
For example: https://hexdocs.pm/elixir/main/search.html?q=%25foo

Probably something to do with the signing of the cloud storage requests on fastly. Originally reported here: https://github.com/elixir-lang/ex_doc/issues/1604

**Comment by rhcarvalho** [comment]
Just ran into this for what should be a valid query, searching for "<%%" on EEx docs :smile: 

https://hexdocs.pm/eex/search.html?q=%3C%25%25

<details>

Response 403

```xml
<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidSecurity</Code><Message>The provided security credentials are not valid.</Message><Details>Request was not signed or contained a malformed signature</Details></Error>
```

</details>

Does this depend on private infrastructure limited to hexdocs maintainers?
