### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by JowaDev** [hexpm/hexdocs#40]
The documentation contains a small error; the exclamation point is missing in the output.

https://hexdocs.pm/elixir/basic-types.html

![image](https://github.com/hexpm/hexdocs/assets/16623250/4228506e-58e2-421c-8d93-e254369ec59c)

**Comment by wojtekmach** [comment]
Please send a PR to elixir-lang/elixir which contains that documentation source code!

**Comment by JowaDev** [comment]
> Please send a PR to elixir-lang/elixir which contains that documentation source code!

[Here](https://github.com/elixir-lang/elixir/edit/main/lib/elixir/pages/getting-started/basic-types.md) the documentation is correct but not in production on this [link](https://hexdocs.pm/elixir/basic-types.html).

**Comment by ericmj** [comment]
The development docs are here https://hexdocs.pm/elixir/main/basic-types.html.
