### ISSUE TITLE
Searching for atoms on hexdocs only works if the colon is included

### ISSUE THREAD

**Issue by lardcanoe** [hexpm/hexdocs#43]
Apologies if this is an ex_doc bug and not hexdocs.

Go to https://hexdocs.pm/phoenix_live_view and search for `temporary_assigns` and it finds no results. If you instead search for `:temporary_assigns` you get results.

https://hexdocs.pm/phoenix_live_view/search.html?q=temporary_assigns
vs
https://hexdocs.pm/phoenix_live_view/search.html?q=%3Atemporary_assigns

**Comment by wojtekmach** [comment]
This is an ExDoc issue, could you re-open it there? It might be tricky but definitely worth investigating
